name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
jobs:
  announce:
    name: Announce
    runs-on: ubuntu-latest

    steps:
      - uses: oprypin/find-latest-tag@v1
        id: version
        with:
          repository: $GITHUB_REPOSITORY
          prefix: v

      - name: Announce
        uses: ethomson/send-tweet-action@v1
        with:
          status: "Version ${{ steps.version.outputs.tag }} of $GITHUB_REPOSITORY has been released to Maven Central https://github.com/$GITHUB_REPOSITORY"
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET_KEY }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
